baseURL = 'https://institut-source-anahata.fr'
languageCode = 'fr-fr'
title = "Source d'Anāhata"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5