[theme]
  primary = "#6BDDB0"
  primary_light = "#DDF7EC"
  primary_dark = "#00C27B"
  
  background_default = "#FDFBF7" # Fond crème
  background_paper = "#F4F0E6"   # Fond sable
  
  text_main = "#3D3D3D"          # Texte principal
  text_muted = "#71717A"         # Texte secondaire / grisé
  
  button_bg = "#3D3D3D"          # Couleur du bouton principal
  button_text = "#FFFFFF"        # Texte du bouton principal

[seo]
  description = "Institut de bien-être à Prenois (21370). Massages, soins visage, épilations, onglerie et beauté du regard dans un espace chaleureux dédié à votre relaxation."
  author = "Source d'Anahata"
  image = "images/accueil/cabine-vue-ensemble-paysage.jpg"